import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Edge Config Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
      </Head>

      <main className={styles.main}>
        <form action="?" method="POST">
          <div className="g-recaptcha" data-sitekey="6LdeiaIlAAAAACF7MRV7Fl6QFiTM_A-XGZ-sgH4C"></div>
          <br/>
          <input type="submit" value="Submit"/>
        </form>
        
      </main>

      <footer className={styles.footer}>
    
      </footer>
    </div>
  )
}
