import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReCAPTCHA from "react-google-recaptcha";

function onChange(value : any) {
  console.log("Captcha value:", value);
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Edge Config Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className='h1'>Vercel Edge Config Demo</h1>
        </div>

        <ReCAPTCHA
          sitekey="6LdeiaIlAAAAACF7MRV7Fl6QFiTM_A-XGZ-sgH4C"
          onChange={onChange}
        />,
        
      </main>
    
    </div>
  )
}
